"""add expected goals conceded to player stats

Revision ID: 406a1f48840f
Revises: 87031b491db1
Create Date: 2026-09-09 17:06:54.629245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406a1f48840f'
down_revision: Union[str, Sequence[str], None] = '87031b491db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_gameweek_stats', sa.Column('expected_goals_conceded_per_90', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_gameweek_stats', 'expected_goals_conceded_per_90')
    # ### end Alembic commands ###
