"""add defensive contribution and expected goals to player stats

Revision ID: 79335413205c
Revises: 406a1f48840f
Create Date: 2026-09-09 21:25:47.863946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79335413205c'
down_revision: Union[str, Sequence[str], None] = '406a1f48840f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_gameweek_stats', sa.Column('defensive_contribution_per_90', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('player_gameweek_stats', sa.Column('expected_goals_per_90', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_gameweek_stats', 'expected_goals_per_90')
    op.drop_column('player_gameweek_stats', 'defensive_contribution_per_90')
    # ### end Alembic commands ###
