"""add fixtures

Revision ID: 87031b491db1
Revises: 7670fe2c9076
Create Date: 2026-09-09 16:28:15.677068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87031b491db1'
down_revision: Union[str, Sequence[str], None] = '7670fe2c9076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=True),
    sa.Column('team_h_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_h_difficulty', sa.Integer(), nullable=False),
    sa.Column('team_a_difficulty', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_h_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixtures')
    # ### end Alembic commands ###
