"""widen per-90 stat columns to prevent overflow

Revision ID: c0d9894bcc4f
Revises: 79335413205c
Create Date: 2026-09-09 21:28:38.095131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d9894bcc4f'
down_revision: Union[str, Sequence[str], None] = '79335413205c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_gameweek_stats', 'expected_goals_conceded_per_90',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('player_gameweek_stats', 'defensive_contribution_per_90',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('player_gameweek_stats', 'expected_goals_per_90',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_gameweek_stats', 'expected_goals_per_90',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('player_gameweek_stats', 'defensive_contribution_per_90',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('player_gameweek_stats', 'expected_goals_conceded_per_90',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
