"""add player gameweek stats

Revision ID: d96f8624f7de
Revises: cd71a2266917
Create Date: 2026-09-09 13:02:16.696624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96f8624f7de'
down_revision: Union[str, Sequence[str], None] = 'cd71a2266917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_gameweek_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('pulled_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('form', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_gameweek_stats_player_id_gameweek', 'player_gameweek_stats', ['player_id', 'gameweek'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_gameweek_stats_player_id_gameweek', table_name='player_gameweek_stats')
    op.drop_table('player_gameweek_stats')
    # ### end Alembic commands ###
