"""add match scores to fixtures

Revision ID: f1f03911618e
Revises: c0d9894bcc4f
Create Date: 2026-09-13 21:41:13.482571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f03911618e'
down_revision: Union[str, Sequence[str], None] = 'c0d9894bcc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('team_h_score', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('team_a_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'team_a_score')
    op.drop_column('fixtures', 'team_h_score')
    # ### end Alembic commands ###
